# Generated by Django 4.2.7 on 2023-12-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Порядковый номер')),
                ('overlay_text', models.CharField(max_length=255, verbose_name='Текст')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.image', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка на слайдере',
                'verbose_name_plural': 'Картинка на слайдере',
            },
        ),
    ]
