# Generated by Django 4.2.7 on 2023-12-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_indexsliderimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created_date'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='indexsliderimage',
            options={'ordering': ['index'], 'verbose_name': 'Картинка на слайдере', 'verbose_name_plural': 'Картинка на слайдере'},
        ),
        migrations.AddField(
            model_name='indexsliderimage',
            name='link',
            field=models.CharField(default='https://vk.com', max_length=255, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
