# Generated by Django 4.2.7 on 2023-12-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_image_options_alter_indexsliderimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexsliderimage',
            options={'ordering': ['index'], 'verbose_name': 'Картинка на слайдере', 'verbose_name_plural': 'Картинки на слайдере'},
        ),
        migrations.CreateModel(
            name='IndexTileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlay_text', models.CharField(max_length=255, verbose_name='Текст')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('index', models.IntegerField(verbose_name='Порядковый номер')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.image', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка в плитке',
                'verbose_name_plural': 'Картинки на плитке',
                'ordering': ['index'],
            },
        ),
    ]
